# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e323327fe87982a96744205f97c7585f01840cc35a2a74ea29ac3edc128342839d8e8b064bc264989c6709da226cd9c834f585a4f45c7357a0de5b142e7159c3

test:
  secret_key_base: 9fc651a0b7a0406eef751ef727ee01744543196b6188d23d235e4a3aade7cf4c19fbc41b0d7aafe1d885f117efcba530c09eb5d706d0128f9a17f19d2d0fa1f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
